---
label: Chart
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: introduction
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Introduction
- name: placeholder_id
  type: text
  config:
    required: true
  label: Placeholder ID
- name: explanation
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Explanation
