---
label: Chart
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: show_title
  type: boolean
  label: Show Title
  default: true
- name: introduction
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Introduction
- name: explanation
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Explanation
- name: placeholder_id
  type: text
  config:
    required: true
  label: Placeholder ID
- name: object
  type: text
  config:
    required: false
  label: Object
- name: appearance
  type: select
  default: Centered
  config:
    required: false
    options:
    - Centered
    - Large
    - Full-bleed
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Appearance
- name: hidden
  type: boolean
  label: Hidden
  default: true
